### ISSUE TITLE
Failed to install the android demo app from App Center on same devices

### ISSUE THREAD

**Issue by carmenlau** [authgear/authgear-sdk-js#114]
Failed to install the app on devices:
Nokia 8.1 (10), Google Pixel 3 (11)

Can install the app on devices:
Samsung C7 Pro (8.0), Nokia 7.2 (10)

There is error "App not installed" when the device failed to install the app. 

Error:
```
failed to install javasample-release.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package com.oursky.authgeartest]
```

**Comment by louischan-oursky** [comment]
According to this comment https://github.com/microsoft/appcenter/issues/1990#issuecomment-861053082

The reason is due to the version of AndroidSigning task of appcenter not recent enough. However, when I checked the build log of the available recent builds, the version is recent enough. And I can install the app on Google Pixel 3 Android 11. So I am going to close this.
